# Generated by rust2rpm 27
%bcond check 1

%global crate gitui

Name:           rust-gitui
Version:        0.27.0
Release:        %autorelease
Summary:        Blazing fast terminal-ui for git

License:        MIT
URL:            https://crates.io/crates/gitui
Source:         %{crates_source}
# Manually created patch for downstream crate metadata changes
# * remove feature for building / statically linking vendored OpenSSL sources
# * relax parking_lot_core dependency from =0.9.10 to ^0.9.10
# * update ron (to 0.9):
#   https://github.com/gitui-org/gitui/commit/5755c096b42553de98490cf788dff1a4925bc574
# * allow unicode-truncate 1.0
# * bump struct-patch to 0.9
#   https://github.com/gitui-org/gitui/pull/2583
Patch:          gitui-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  /usr/bin/git

%global _description %{expand:
Blazing fast terminal-ui for git.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.md
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc FAQ.md
%doc KEY_CONFIG.md
%doc NIGHTLIES.md
%doc README.md
%doc THEMES.md
%{_bindir}/gitui

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
export GITUI_RELEASE=1
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
export GITUI_RELEASE=1
%cargo_install

%if %{with check}
%check
export GITUI_RELEASE=1
%cargo_test
%endif

%changelog
%autochangelog
