[features]
hide = ["termwiz"]

[package]
cargo-toml-patch-comments = [
    """
    Drop unused dependency font8x8.
    https://github.com/ratatui/ratatui/pull/1777
    """,
    "Do not depend on criterion; it is needed only for benchmarks.",
    """
    Do not depend on fakeit; it is needed only for benchmarks.
    (examples/table.rs is also removed)
    """,
    "Remove octocrab dependency and examples/async.rs",
]

[scripts]
prep.post = [
    "# remove executable bits from source files",
    "find -type f -executable -print -exec chmod -x {} +",
]

[tests]
skip = [
    "buffer::buffer::Buffer::pos_of",
    "buffer::buffer::tests::pos_of_panics_on_out_of_bounds",
]
comments = [
    "- buffer::buffer::Buffer::pos_of this one panics only if in debug.",
    "- buffer::buffer::tests::pos_of_panics_on_out_of_bounds same test as above",
]

