[package]
cargo-toml-patch-comments = [
    "Drop pretty_assertions_sorted dependency",
]

[scripts]
prep.post = [
    "# Remove pretty_assertions_sorted usage",
    "sed -i '/use pretty_assertions_sorted/d' src/patch.rs",
    "sed -i 's/assert_eq_sorted/assert_eq/' src/patch.rs",
]
